### ISSUE TITLE
Not builded project after `npm run start`

### ISSUE THREAD

**Issue by Semigradsky** [dihar/fast-framework#6]
In console:
> E:\_test\fast-framework>npm run start
>
>> fast-framework@0.1.0 start E:\_test\fast-framework
>> node app & gulp
>
>trying to create app on port 4422...
>FF listening on port 4422!

In browser console:
![image](https://cloud.githubusercontent.com/assets/1198848/20867641/82293a90-ba5a-11e6-9581-089fec27c739.png)

**Comment by dihar** [comment]
Дмитрий, Можешь по-подробней описать, что было в консоле? Команда `npm run start` запускает сервер на ноде и запускает gulp со всеми тасками, которые выводятся в консоль при запуске. Чего ты не отобарзил. Далее gulp запускает прокси сервер на 3000 порту (если он не занят) , проксируется порт 4422. ВОзможно у тебя не прошёл билд gulp. Убедись что билд прошёл. Сейчас не могу понять, почему файлов нету. На какой системе запуск производишь?  И спасибо, что нашёл время поторогать проектик=)

**Comment by Semigradsky** [comment]
Привет, переходим на великий и могучий, так будет проще)

- Склонировал проект на другой машине (Windows 10, node 6.5.0,npm 3.10.3). `npm install`
- В gulpfile.js добавил console.log
- Запустил `npm run start`
Судя по выводу в консоль, gulp не запустился.

**Comment by dihar** [comment]
Всё ясно, тут тоже мой косяк. Оператор &(параллельное выполнение программ) не работает на винде, сейчас перезалью с &&.

**Comment by Semigradsky** [comment]
@dihar я тоже сначала про это думал.

С `node app && gulp` результат аналогичный. Наверное из-за того, что процесс node так и не завершается. Тут надо что-то вроде https://github.com/kimmobrunfeldt/concurrently

**Comment by dihar** [comment]
concurrently – это вариант, но он разовый. Легче будет тогда просто для винды запускать процесс в двух вкладках терминала, чем постоянной устанавливать глобальный алиас.
